### ISSUE TITLE
Do not lose details of undocumented exceptions

### ISSUE THREAD

**Issue by mikkorantalainen** [henrik-lindqvist/safs#3] opened 2019-12-23 13:09 UTC
The existing code blindly catches any exception, discards all info about the actual exception and throws NoSuchFileException instead. This code should try to emit at least enough info that the actual exception can be figured out.

https://github.com/henrik-lindqvist/safs/blob/106d4d154410471e774a1e2e6f677926d2fd351b/safs-android/src/main/java/com/llamalab/safs/android/AndroidFileSystemProvider.java#L621

**Comment by henrik-lindqvist** [comment] 2019-12-23 18:39
Duplicate of #2

**Closed as completed by henrik-lindqvist** 2019-12-23 18:39 UTC
